[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "django-mptt-admin"
version = "2.10.0"
description = "Django-mptt-admin provides a nice Django Admin interface for Mptt models"
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICENSE.rst"]
authors = [{ name = "Marco Braak", email = "marco.braak@planet.nl" }]
requires-python = ">=3.10"
dependencies = ["django-mptt"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Framework :: Django",
    "Framework :: Django :: 5.2",
    "Framework :: Django :: 6.0",
    "Framework :: Django :: 6.1",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Implementation :: CPython",
]

[project.urls]
Homepage = "https://github.com/mbraak/django-mptt-admin"
Documentation = "https://mbraak.github.io/django-mptt-admin/"
Changelog = "https://mbraak.github.io/django-mptt-admin/#changelog"

[tool.setuptools.packages.find]
include = ["django_mptt_admin*"]
