[tox]
envlist = py313-django52,py314-django60,py314-django61

[testenv]
changedir = {toxinidir}/example_project
setenv =
    PYTHONWARNINGS = default
deps =
    -r{toxinidir}/example_project/requirements_test.txt
    django52: Django>=5.2,<5.3
    django60: Django>=6.0,<6.1
    django61: Django==6.1a1
commands =
    python -Wd manage.py test django_mptt_example
basepython =
    py313: python3.13
    py314: python3.14
