# Generated by Django 4.0 on 2021-04-25 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_mptt_example", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="level",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="country",
            name="lft",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="country",
            name="rght",
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
