name: Test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r example_project/requirements_test.txt
        python -m playwright install
        pip install -r example_project/requirements_travis.txt
        pip install -e .
    - name: Test
      run: |
        python -Wd example_project/manage.py test django_mptt_example
